#name: coffeshop
#description: A new Flutter project.
#
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev
#
#
#
#
#version: 1.0.0+1
#
#environment:
#  sdk: '>=3.1.0 <4.0.0'
#
#
#dependencies:
#  flutter:
#    sdk: flutter
#  http: ^1.1.2
#  cupertino_icons: ^1.0.2
#  google_fonts: ^2.0.0
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#    http: ^1.1.2
#
#
#
#  flutter_lints: ^2.0.0
#
#
#flutter:
#
#
#  uses-material-design: true
#
#
#
#  assets:
#    - assets/coffewall.jpg
#    - assets/cups.jpg
#    - assets/imge1.png
#    - assets/login.jpg
#    - assets/time.jpeg
#    - assets/cup.jpg
#    - assets/coop.jpg
#    - assets/timme.jpeg


name: realEstate
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  line_awesome_flutter: ^2.0.0
  image_picker: ^0.8.4+3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
#    - assets/coffewall.jpg
#    - assets/cups.jpg
#    - assets/imge1.png
#    - assets/login.jpg
#    - assets/time.jpeg
#    - assets/cup.jpg
#    - assets/coop.jpg
#    - assets/timme.jpeg
    - assets/



