# Generated by Django 5.0 on 2023-12-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketTask', '0002_coffeeshop_remove_reservation_guest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.DeleteModel(
            name='CoffeeShop',
        ),
    ]
